const categories=[
 {name:'Music',emoji:'♫',image:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=700&q=80'},
 {name:'Tech',emoji:'⌘',image:'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=700&q=80'},
 {name:'Lifestyle',emoji:'✦',image:'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=700&q=80'},
 {name:'Sports',emoji:'◉',image:'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=700&q=80'},
 {name:'Comedy',emoji:'☺',image:'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=700&q=80'},
 {name:'Food',emoji:'⌁',image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=700&q=80'}
];
const events=[
 {id:1,title:'Neon Nights Festival',category:'Music',date:'Fri · 18 Sep',location:'Riverfront Arena · Pune',price:'₹999',desc:'An immersive night of live electronic music, visual art and food under the city lights.',image:'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=85'},
 {id:2,title:'Build Better Products',category:'Tech',date:'Sat · 19 Sep',location:'Horizon Labs · Bengaluru',price:'₹1,499',desc:'A practical product conference for builders, designers and ambitious founders.',image:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=900&q=85'},
 {id:3,title:'Sunday Social Club',category:'Lifestyle',date:'Sun · 20 Sep',location:'The Courtyard · Mumbai',price:'Free',desc:'Coffee, creators, design talks and the kind of Sunday you wish lasted longer.',image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=85'},
 {id:4,title:'City Lights Run',category:'Sports',date:'Sun · 20 Sep',location:'Mula-Mutha Trail · Pune',price:'₹499',desc:'A community 10K run with a sunrise route, hydration stations and recovery zone.',image:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85'},
 {id:5,title:'Stand-Up After Dark',category:'Comedy',date:'Sat · 19 Sep',location:'Laugh Room · Delhi',price:'₹699',desc:'Four sharp comics, one tiny room and two hours of very questionable decisions.',image:'https://images.unsplash.com/photo-1603190287605-e6ade32fa852?auto=format&fit=crop&w=900&q=85'},
 {id:6,title:'The Dinner Table',category:'Food',date:'Thu · 24 Sep',location:'Olive Garden · Mumbai',price:'₹1,799',desc:'A six-course chef-led dining experience built around local ingredients and stories.',image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85'},
 {id:7,title:'Indie Frequencies',category:'Music',date:'Fri · 25 Sep',location:'Studio 9 · Pune',price:'₹799',desc:'A handpicked lineup of indie artists in an intimate listening-room setting.',image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85'},
 {id:8,title:'Design Systems Lab',category:'Tech',date:'Sat · 26 Sep',location:'Maker House · Mumbai',price:'₹1,199',desc:'Design, ship and scale a coherent system with real-world exercises and critique.',image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=85'}
];
let activeCategory='All';
let saved=JSON.parse(localStorage.getItem('eventlySaved')||'[]');
const $=s=>document.querySelector(s);
const categoryGrid=$('#categoryGrid'),eventGrid=$('#eventGrid'),resultCount=$('#resultCount'),emptyState=$('#emptyState'),toast=$('#toast');
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function renderCategories(){categoryGrid.innerHTML=categories.map(c=>`<article class="category-card" data-cat="${c.name}" style="background-image:url('${c.image}')"><span class="emoji">${c.emoji}</span><h3>${c.name}</h3></article>`).join('');categoryGrid.querySelectorAll('.category-card').forEach(card=>card.onclick=()=>selectCategory(card.dataset.cat))}
function getFiltered(){const q=$('#searchInput').value.trim().toLowerCase(),loc=$('#locationFilter').value;return events.filter(e=>(activeCategory==='All'||e.category===activeCategory)&&(!q||`${e.title} ${e.category} ${e.location}`.toLowerCase().includes(q))&&(loc==='All'||e.location.includes(loc)))}
function renderEvents(){const list=getFiltered();resultCount.textContent=`${list.length} ${list.length===1?'event':'events'}`;emptyState.classList.toggle('hidden',list.length!==0);eventGrid.classList.toggle('hidden',list.length===0);eventGrid.innerHTML=list.map(e=>{const isSaved=saved.includes(e.id);return `<article class="event-card"><div class="event-image-wrap"><img class="event-image" src="${e.image}" alt="${e.title}" loading="lazy"><button class="heart ${isSaved?'saved':''}" data-id="${e.id}" aria-label="${isSaved?'Remove from saved':'Save'}">${isSaved?'♥':'♡'}</button></div><div class="event-body"><div class="event-meta">${e.date} · ${e.category}</div><h3>${e.title}</h3><div class="event-location">${e.location}</div><div class="event-footer"><span class="price">${e.price}</span><button class="details-btn" data-details="${e.id}">Details →</button></div></div></article>`}).join('');eventGrid.querySelectorAll('.heart').forEach(b=>b.onclick=()=>toggleSaved(Number(b.dataset.id)));eventGrid.querySelectorAll('.details-btn').forEach(b=>b.onclick=()=>openEvent(Number(b.dataset.details)))}
function selectCategory(cat){activeCategory=cat;document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));renderEvents();document.querySelector('#discover').scrollIntoView({behavior:'smooth'});}
function toggleSaved(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('eventlySaved',JSON.stringify(saved));renderEvents();updateSavedCount();showToast(saved.includes(id)?'Saved to your schedule':'Removed from your schedule')}
function updateSavedCount(){const el=$('#savedStat');if(el)el.textContent=saved.length}
function openEvent(id){const e=events.find(x=>x.id===id);const modal=$('#eventModal');const isSaved=saved.includes(id);$('#modalContent').innerHTML=`<img class="modal-inner-img" src="${e.image}" alt="${e.title}"><div class="modal-body"><p class="eyebrow">${e.date} · ${e.category}</p><h2>${e.title}</h2><p class="info">${e.location}</p><p>${e.desc}</p><div class="modal-actions"><button class="primary-btn" onclick="toggleSaved(${e.id});openEvent(${e.id})">${isSaved?'Remove from schedule':'Save to schedule'}</button><button class="secondary-btn" onclick="$('#eventModal').close()">Close</button></div></div>`;modal.showModal()}
$('#searchBtn').onclick=()=>{renderEvents();document.querySelector('.event-section').scrollIntoView({behavior:'smooth'});};$('#searchInput').addEventListener('input',renderEvents);$('#locationFilter').addEventListener('change',renderEvents);
document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>selectCategory(b.dataset.category));$('#clearCategory').onclick=()=>selectCategory('All');$('#resetFilters').onclick=()=>{$('#searchInput').value='';$('#locationFilter').value='All';selectCategory('All')};
$('#eventModal').addEventListener('click',e=>{if(e.target.id==='eventModal')$('#eventModal').close()});$('#modalClose').onclick=()=>$('#eventModal').close();
$('#profileBtn').onclick=()=>{$('#profileModal').showModal();updateSavedCount()};$('#profileClose').onclick=()=>$('#profileModal').close();$('#profileDone').onclick=()=>$('#profileModal').close();
$('#scheduleBtn').onclick=()=>{$('#calendar').scrollIntoView({behavior:'smooth'});showToast(saved.length?`You have ${saved.length} saved event${saved.length===1?'':'s'}`:'Save events to build your schedule')};
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('eventlyTheme',document.body.classList.contains('dark')?'dark':'light')};
if(localStorage.getItem('eventlyTheme')==='dark')document.body.classList.add('dark');
renderCategories();renderEvents();updateSavedCount();
