const courses=[
{id:'javascript',title:'Modern JavaScript: From Zero to Production',category:'Development',level:'Intermediate',rating:'4.9',students:'8.2k',lessons:42,image:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=85',desc:'Build confident JavaScript skills through APIs, async patterns and real projects.'},
{id:'uiux',title:'Product Design & UI Systems',category:'Design',level:'Beginner',rating:'4.8',students:'6.4k',lessons:31,image:'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=900&q=85',desc:'Learn to turn ideas into clear, beautiful interfaces and reusable design systems.'},
{id:'data',title:'Data Analytics with Excel & SQL',category:'Data',level:'Beginner',rating:'4.9',students:'9.7k',lessons:38,image:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=85',desc:'Make better decisions with practical analytics, dashboards and SQL workflows.'},
{id:'strategy',title:'Strategic Thinking for Modern Business',category:'Business',level:'Intermediate',rating:'4.8',students:'4.3k',lessons:26,image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85',desc:'Build frameworks for prioritization, decision-making and sustainable growth.'},
{id:'react',title:'React & Frontend Architecture',category:'Development',level:'Advanced',rating:'4.9',students:'7.1k',lessons:48,image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85',desc:'Design maintainable React applications with modern frontend architecture.'},
{id:'branding',title:'Brand Identity: From Idea to Impact',category:'Design',level:'Intermediate',rating:'4.7',students:'3.8k',lessons:29,image:'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=900&q=85',desc:'Shape memorable brands with strategy, typography, color and visual direction.'}
];
const state={filter:'All',query:'',saved:JSON.parse(localStorage.getItem('learnifySaved')||'[]')};
const grid=document.getElementById('courseGrid'),empty=document.getElementById('emptyState'),modal=document.getElementById('modal'),modalContent=document.getElementById('modalContent'),toast=document.getElementById('toast');
function render(){const list=courses.filter(c=>(state.filter==='All'||c.category===state.filter)&&`${c.title} ${c.category} ${c.level}`.toLowerCase().includes(state.query.toLowerCase()));grid.innerHTML=list.map(c=>`<article class="course-card"><div class="course-image"><img src="${c.image}" alt="${c.title}" loading="lazy"><span class="course-tag">${c.category}</span><button class="heart ${state.saved.includes(c.id)?'saved':''}" data-save="${c.id}" aria-label="Save course">${state.saved.includes(c.id)?'♥':'♡'}</button></div><div class="course-body"><h3>${c.title}</h3><p>${c.desc}</p><div class="course-info"><span>${c.level} · ${c.lessons} lessons</span><strong>★ ${c.rating}</strong></div><button class="btn btn-outline small course-open" data-course="${c.id}" style="margin-top:14px;width:100%;justify-content:center">View course</button></div></article>`).join('');empty.style.display=list.length?'none':'block'}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
function openCourse(id){const c=courses.find(x=>x.id===id);if(!c)return;modalContent.innerHTML=`<p class="eyebrow">${c.category.toUpperCase()} · ${c.level.toUpperCase()}</p><h2>${c.title}</h2><p style="color:var(--muted)">${c.desc}</p><div class="course-info" style="margin:18px 0;padding-bottom:14px;border-bottom:1px solid var(--line)"><span>★ ${c.rating} · ${c.students} learners</span><span>${c.lessons} lessons</span></div><h3>What you'll learn</h3><div class="lesson-list"><div class="lesson">01 · Foundations & mental models <span>12 min</span></div><div class="lesson">02 · Practical workflows <span>18 min</span></div><div class="lesson">03 · Build your first project <span>24 min</span></div><div class="lesson">04 · Real-world challenge <span>31 min</span></div></div><button class="btn btn-primary" id="startCourse">Start learning →</button>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.getElementById('startCourse').onclick=()=>{closeModal();showToast(`You're enrolled in ${c.title}`);};}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
grid.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];localStorage.setItem('learnifySaved',JSON.stringify(state.saved));render();showToast(state.saved.includes(id)?'Course saved to your library':'Removed from saved courses');return}const open=e.target.closest('.course-open');if(open)openCourse(open.dataset.course)});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;render()}));
document.getElementById('courseSearch').addEventListener('input',e=>{state.query=e.target.value;render()});document.getElementById('searchFocus').onclick=()=>{document.getElementById('courseSearch').focus();document.getElementById('courses').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.getElementById('watchIntro').onclick=()=>{modalContent.innerHTML='<p class="eyebrow">WELCOME TO LEARNIFY</p><h2>A calmer way to learn.</h2><p style="color:var(--muted)">Learnify combines focused lessons, practical projects and a simple progress system so you always know what to learn next.</p><div style="background:#e7eee9;border-radius:12px;padding:34px;text-align:center;font-size:38px;color:var(--forest);margin:20px 0">▶</div><button class="btn btn-primary" data-close>Explore courses →</button>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modalContent.querySelector('[data-close]').onclick=closeModal};
document.getElementById('goalBtn').onclick=()=>showToast('Focus session started — 25 minutes on the clock.');document.getElementById('profileBtn').onclick=()=>{modalContent.innerHTML='<p class="eyebrow">YOUR PROFILE</p><h2>Welcome back, Danni.</h2><p style="color:var(--muted)">You have completed 68% of your current course and maintained a 7-day learning streak.</p><button class="btn btn-primary" data-close>Back to learning</button>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modalContent.querySelector('[data-close]').onclick=closeModal};
const menu=document.getElementById('mobileNav');document.getElementById('menuBtn').onclick=()=>menu.classList.toggle('open');menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));document.querySelectorAll('[data-course]').forEach(btn=>btn.addEventListener('click',()=>openCourse(btn.dataset.course)));
render();
