const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fields=['decisionTitle','startingCash','monthlyIncome','monthlyExpenses','horizon','optionAAmount','optionAName','optionBAmount','optionBName'];
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Math.round(n));
const compact=n=>n>=100000?`₹${(n/100000).toFixed(1)}L`:n>=1000?`₹${Math.round(n/1000)}k`:money(n);
const getNum=id=>Math.max(0,Number($('#'+id).value)||0);
let reverse=false,insightIndex=0;
const insights=[
 ['Liquidity is your hidden variable.','A large upfront purchase changes the flexibility of every decision that follows. The simulation isolates that effect instead of treating the purchase as a one-time event.'],
 ['Small monthly changes compound quickly.','Changing monthly income or expenses shifts every projected month, so stress-testing those variables can reveal a very different runway.'],
 ['The horizon changes the story.','Short horizons emphasize liquidity. Longer horizons make recurring monthly behavior and compounding gaps much more visible.'],
 ['Compare paths, not labels.','The simulator does not choose for you. It makes the assumptions and consequences visible so you can decide what matters.']
];
function values(){return {cash:getNum('startingCash'),income:getNum('monthlyIncome'),expenses:getNum('monthlyExpenses'),months:Math.min(24,Math.max(3,getNum('horizon'))),a:getNum('optionAAmount'),b:getNum('optionBAmount')}}
function path(v,spend){return Array.from({length:v.months+1},(_,i)=>v.cash-spend+i*(v.income-v.expenses));}
function drawChart(a,b){const canvas=$('#forecastChart'),ctx=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);const all=[...a,...b],min=Math.min(0,...all),max=Math.max(...all),range=Math.max(1,max-min);const px=(i)=>20+i/(a.length-1)*(w-40),py=(n)=>h-20-(n-min)/range*(h-40);
function line(data,gradient){const g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,gradient[0]);g.addColorStop(1,gradient[1]);ctx.strokeStyle=g;ctx.lineWidth=3;ctx.lineJoin='round';ctx.beginPath();data.forEach((n,i)=>{const x=px(i),y=py(n);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();return {g}}
line(a,['#a855f7','#c084fc']);line(b,['#06b6d4','#67e8f9']);
const fill=ctx.createLinearGradient(0,0,0,h);fill.addColorStop(0,'rgba(6,182,212,.16)');fill.addColorStop(1,'rgba(6,182,212,0)');ctx.fillStyle=fill;ctx.beginPath();data=>{};ctx.moveTo(px(0),h);b.forEach((n,i)=>ctx.lineTo(px(i),py(n)));ctx.lineTo(px(b.length-1),h);ctx.closePath();ctx.fill();
canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect(),i=Math.max(0,Math.min(a.length-1,Math.round((e.clientX-r.left)/(r.width)*(a.length-1))));const t=$('#chartTooltip');t.style.display='block';t.style.left=`${Math.min(r.width-145,Math.max(6,e.clientX-r.left+12))}px`;t.style.top='12px';t.textContent=`MONTH ${i} · A ${compact(a[i])} · B ${compact(b[i])}`};canvas.onmouseleave=()=>$('#chartTooltip').style.display='none';}
function simulate(){const v=values(),a=path(v,v.a),b=path(v,v.b),endA=a.at(-1),endB=b.at(-1),gap=Math.abs(endA-endB),flex=v.income-v.expenses,stability=Math.max(35,Math.min(96,Math.round(92-(v.a-v.b)/Math.max(1,v.cash+v.income*v.months)*100)));$('#cashGap').textContent=money(gap);$('#stabilityScore').textContent=stability;$('#forecastLabel').textContent=`${v.months} MONTH FORECAST`;$('#endLabel').textContent=`${v.months} MO`;$('#endA').textContent=compact(endA);$('#endB').textContent=compact(endB);$('#deltaA').textContent=`${endA-v.cash>=0?'+':''}${compact(endA-v.cash)}`;$('#deltaB').textContent=`${endB-v.cash>=0?'+':''}${compact(endB-v.cash)}`;$('#flexibility').textContent=compact(flex);$('#shiftValue').textContent=`${Math.round(gap/Math.max(1,v.cash)*100)}%`;$('#cardATitle').textContent=$('#optionAName').value||'Option A';$('#cardBTitle').textContent=$('#optionBName').value||'Option B';$('#cardAValue').textContent=money(endA);$('#cardBValue').textContent=money(endB);$('#bufferMonths').textContent=`${(endB/Math.max(1,v.expenses)).toFixed(1)} months`;$('#sensitivityValue').textContent=`+${money(v.income*.22)}`;drawChart(a,b);$('#scenarioState').textContent='UPDATED';}
function loadSample(){const sample={decisionTitle:'Take a course or keep saving?',startingCash:110000,monthlyIncome:50000,monthlyExpenses:27000,horizon:12,optionAAmount:28000,optionAName:'Buy the course',optionBAmount:0,optionBName:'Keep saving'};Object.entries(sample).forEach(([k,v])=>$('#'+k).value=v);simulate();document.querySelector('#simulator').scrollIntoView({behavior:'smooth'});}
function shuffleInsight(){const idx=(insightIndex+1)%insights.length;insightIndex=idx;$('#insightTitle').textContent=insights[idx][0];$('#insightText').textContent=insights[idx][1];}
$('#simulateBtn').addEventListener('click',simulate);$('#randomScenarioBtn').addEventListener('click',loadSample);$('#shuffleInsightBtn').addEventListener('click',shuffleInsight);$('#reverseBtn').addEventListener('click',()=>{reverse=!reverse;const cards=$$('.future-card');const grid=cards[0].parentElement;grid.append(reverse?cards[1]:cards[0]);grid.append(reverse?cards[0]:cards[1]);});$('#themeToggle').addEventListener('click',()=>document.body.classList.toggle('light'));fields.forEach(id=>$('#'+id).addEventListener('input',simulate));
$$('.text-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('#simulator').scrollIntoView({behavior:'smooth'});$('.input-panel').animate([{boxShadow:'0 0 0 #000'},{boxShadow:'0 0 60px rgba(168,85,247,.25)'},{boxShadow:'0 0 0 #000'}],{duration:1000});}));window.addEventListener('resize',simulate);simulate();