name: Deploy All Projects

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout Repository
      # =========================

      - name: Checkout
        uses: actions/checkout@v4


      # =========================
      # Setup Node
      # =========================

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      # =========================
      # Build Noir-Fragrance
      # =========================

      - name: Install Noir-Fragrance dependencies
        working-directory: Noir-Fragrance
        run: npm ci

      - name: Build Noir-Fragrance
        working-directory: Noir-Fragrance
        run: npm run build


      # =========================
      # Build JobTrack
      # =========================

      - name: Install JobTrack dependencies
        working-directory: job-application-tracker
        run: npm ci

      - name: Build JobTrack
        working-directory: job-application-tracker
        run: npm run build


      # =========================
      # Prepare GitHub Pages
      # =========================

      - name: Prepare GitHub Pages
        run: |
          mkdir pages

          rsync -av \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='Noir-Fragrance' \
            --exclude='job-application-tracker' \
            --exclude='pages' \
            ./ pages/

          mkdir -p pages/Noir-Fragrance
          cp -r Noir-Fragrance/dist/. pages/Noir-Fragrance/

          mkdir -p pages/job-application-tracker
          cp -r job-application-tracker/dist/. pages/job-application-tracker/


      # =========================
      # Setup GitHub Pages
      # =========================

      - name: Setup Pages
        uses: actions/configure-pages@v5


      # =========================
      # Upload Pages
      # =========================

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages


  # =========================
  # Deploy
  # =========================

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4